import os
import subprocess
from fastapi import FastAPI, HTTPException

app = FastAPI()

# Define the input directory path relative to the application root
DATA_DIRECTORY = os.path.join("./data")

def run_diffdock_inference(pdb_contents: str, ligand: str, complex_name: str, output_dir: str) -> dict:
    """
    Run the DiffDock inference process.

    Args:
        pdb_contents (str): The PDB contents of the protein complex.
        ligand (str): The ligand name.
        complex_name (str): The name of the complex.    
    """

    # Write the provided PDB contents to the expected file
    pdb_input_path = os.path.join(DATA_DIRECTORY, "input", complex_name + ".pdb")
    with open(pdb_input_path, "w") as pdb_file:
        pdb_file.write(pdb_contents)
    
    # Ensure the output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    # Build the inference command based on the documentation
    command = [
        "python", "-m", "inference",
        "--protein_path", pdb_input_path,
        "--ligand", ligand,
        "--complex_name", complex_name,
        "--save_visualisation",
        "--out_dir", output_dir
    ]
    
    # Run the inference process and capture output
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        raise Exception("Inference failed: " + result.stderr)

    results = {
        "rank1" : os.path.join(DATA_DIRECTORY, "results", complex_name, "rank1.sdf"),
    }

    return results   

@app.post("/infer")
async def infer(pdb_contents: str, ligand: str, complex_name: str):
    output_dir = os.path.join(DATA_DIRECTORY, "results", complex_name)
    try:
        results = run_diffdock_inference(pdb_contents = pdb_contents, ligand = ligand, complex_name = complex_name, output_dir = output_dir)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    
    # Path to the output PDB file generated by the inference process
    if not os.path.exists(output_dir):
        raise HTTPException(status_code=404, detail="Output PDB file not found.")
    
    return results

    
